version: '3.8'
services:
  app:
    build: .
    container_name: go_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app_network
    restart: always

  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
