server {
    listen 80;
    server_name localhost;

    client_max_body_size 100M;

    # Proxy al backend
    location / {
        proxy_pass http://go_app:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Servir archivos subidos desde /uploads
    location /uploads/ {
        alias /uploads/;
        autoindex on;
        add_header Access-Control-Allow-Origin *;

        # Restricción de acceso por IP
        # allow 192.168.1.0/24;  # Permitir solo una red local específica (subred)
        # allow 123.45.67.89;    # Permitir una IP específica
        # deny all;              # Denegar a todos los demás
    }
}
